# Numpy

## Agenda
- Fundamentals of numpy
  - Advantages
  - Numpy Installation and import
- Arrays
  - Creating Numpy arrays
- Attributes
- Array Functions
  - Arithmetic
  - Statistical
  - String
  - Miscellaneous
- Array Indexing and Slicing

## Fundamentals of Numpy
Numpy (Numerical Python) is a free, open source python library which is primrily used for mathematical computations. it is prefered over the traditional math module in python for math computation as numpy process the data if a faster way than traditional python. Numpy achieves this by utilizing the arrays (Collection of data arranged in a contiguos memory )

In [2]:
import time
import numpy as np

In [18]:
time.time()  # gives the time elapsed since epoch(1-1-1970, 00:00:00) in seconds

1736270803.8289938

In [4]:
time.time() 

1736270162.4233577

In [15]:
X =  np.random.rand(100000000)   # Generated random floating point numbers

In [16]:
start = time.time()
m =  sum(X)/100000000  # mean using traditional python
stop = time.time()
print(stop- start)

12.282127141952515


In [17]:
start = time.time()
m =  np.mean(X)  # mean calculation using numpy library
stop = time.time()
print(stop- start)

0.18876910209655762


Dated -  08-01-2025

In [22]:
# Install numpy
# pip(prefered python installer) install numpy

In [23]:
pip install numpy

In [24]:
## import the library - it allows to use the library and its content for the current file.

import numpy as np

### Creation of arrays using numpy.
There are two ways by which arrays can be formed using numpy
- using the inbulit array() function  - converts other sequential  data structure to form array
- using miscellaneous functions - generates arrays using some conditions.
  
#### Arrays 
arrays is a collection of homogeneous data elements arranged in contiguos manner. These are represented as space seperated values enclosed within square brackets in python. arrays can attain any number of dimensions i.e. an array is python can be 0 dimensional, 1 dimensional, 2 dimensional, n-dimensional. The numpy arrays are often termed as ndarray.

#### creating arrays using array function

In [40]:
# creating a zero dimensional array
## we can create a 0darray by passing a scalar value inside the numpy array function

zero_d_array =  np.array(5)
print(zero_d_array)
print(type(zero_d_array))
## ndarray attributes
print(f'The Number of dimensions is {zero_d_array.ndim}')  # gives the number of dimensions of the array
print(f'The shape of the array is {zero_d_array.shape}') # The number of elements in each dimension
print(f'The Size of the array is {zero_d_array.size}') # Total number of elements in the array
print(f'Elements data type in the array is {zero_d_array.dtype}') # Datatype of the elements of the array

5
<class 'numpy.ndarray'>
The Number of dimensions is 0
The shape of the array is ()
The Size of the array is 1
Elements data type in the array is int32


In [42]:
# creating a One dimensional array
## we can create a 1darray by passing a list of values inside the numpy array function

one_d_array =  np.array([1,2,3,4,5])
print(one_d_array)
print(type(one_d_array))
## ndarray attributes
print(f'The Number of dimensions is {one_d_array.ndim}')  # 1
print(f'The shape of the array is {one_d_array.shape}') # (5,)
print(f'The Size of the array is {one_d_array.size}') # 5
print(f'Elements data type in the array is {one_d_array.dtype}') # int32

[1 2 3 4 5]
<class 'numpy.ndarray'>
The Number of dimensions is 1
The shape of the array is (5,)
The Size of the array is 5
Elements data type in the array is int32


In [43]:
# creating a Two dimensional array
## we can create a 2darray by passing a list of lists of values inside the numpy array function

two_d_array =  np.array([[1,2,3,4,5], [11,12,13,14,15], [21,22, 23, 24, 25]])
print(two_d_array)
print(type(two_d_array))
## ndarray attributes
print(f'The Number of dimensions is {two_d_array.ndim}')  # 2
print(f'The shape of the array is {two_d_array.shape}') # (3,5)
print(f'The Size of the array is {two_d_array.size}') # 15
print(f'Elements data type in the array is {two_d_array.dtype}') # int32

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
<class 'numpy.ndarray'>
The Number of dimensions is 2
The shape of the array is (3, 5)
The Size of the array is 15
Elements data type in the array is int32


In [45]:
## For unequal number of elements in lists

example = np.array([[1,2,3,4,5], [11,12,13,14], [21,22, 23, 24, 25]], dtype = 'object')
print(example)
print(example.shape)

[list([1, 2, 3, 4, 5]) list([11, 12, 13, 14]) list([21, 22, 23, 24, 25])]
(3,)


In [48]:
# creating a Three dimensional array
## we can create a 3darray by passing a list of lists of lists of values inside the numpy array function

three_d_array =  np.array([[[1, 2, 3,4], [4, 5, 6,4], [7, 8, 9,4]],
                         [[10, 11, 12,4], [13, 14, 15,4], [16, 17, 18,4]]])
print(three_d_array)
print(type(three_d_array))
## ndarray attributes
print(f'The Number of dimensions is {three_d_array.ndim}')  # 3
print(f'The shape of the array is {three_d_array.shape}') # (2,3,4)
print(f'The Size of the array is {three_d_array.size}') # 24
print(f'Elements data type in the array is {three_d_array.dtype}') # int32

[[[ 1  2  3  4]
  [ 4  5  6  4]
  [ 7  8  9  4]]

 [[10 11 12  4]
  [13 14 15  4]
  [16 17 18  4]]]
<class 'numpy.ndarray'>
The Number of dimensions is 3
The shape of the array is (2, 3, 4)
The Size of the array is 24
Elements data type in the array is int32


In [49]:
example =  np.array([[1,2,3], [4,5,6], [7,8,9], [11, 12, 13]])

In [54]:
example.dtype

dtype('int32')

In [55]:
print(example.itemsize) # it gives the memory alloted to one value in the array in bytes

4


In [58]:
print(example.data) # gives the memory address of the array block

### Basic Array functions
- transpose
- reshape
- flatten
- ravel
- argmin
- argmax

In [87]:
example =  np.array([728, 482, 564, 926, 285, 156, 434,  22, 807, 719, 472, 999, 531,
       336, 325, 444, 456,  62, 567, 826])

In [88]:
# reshape() -  allows to modify the dimensions of the array with a constraint the new array with modified
# dimensions will have same size as original array
## syntax -  <arrayname>.reshape(<new_shape>). it a creates a modified copy of the array in the
## memory and doesnot alter the original array untill reassigned

In [89]:
print(example.ndim)
print(example.shape)
print(example.size)

1
(20,)
20


In [90]:
example.reshape(2,5,2)

array([[[728, 482],
        [564, 926],
        [285, 156],
        [434,  22],
        [807, 719]],

       [[472, 999],
        [531, 336],
        [325, 444],
        [456,  62],
        [567, 826]]])

In [91]:
example2d = example.reshape(4,5)

In [92]:
print(example2d)

[[728 482 564 926 285]
 [156 434  22 807 719]
 [472 999 531 336 325]
 [444 456  62 567 826]]


In [94]:
## transpose() -  it is used to take transpose of the array similar to matrix i.e. 
# rows are converted to columns and vice versa . it a creates a modified copy of the array in the
# memory and doesnot alter the original array untill reassigned

In [98]:
print(example2d)
print(example2d.shape)

[[728 482 564 926 285]
 [156 434  22 807 719]
 [472 999 531 336 325]
 [444 456  62 567 826]]
(4, 5)


In [100]:
print(example2d.transpose())
print(example2d.transpose().shape)

[[728 156 472 444]
 [482 434 999 456]
 [564  22 531  62]
 [926 807 336 567]
 [285 719 325 826]]
(5, 4)


In [101]:
## flatten() -  used to convert any dimensional array to 1d array
example2d.flatten()

array([728, 482, 564, 926, 285, 156, 434,  22, 807, 719, 472, 999, 531,
       336, 325, 444, 456,  62, 567, 826])

In [103]:
## ravel() -  used to convert any dimensional array to 1 dimensional array. it also allow to read the array in 
# either row major or column major form
## syntax -  np.ravel(<arrayname>, order = <'F','C','A','K'>)

In [104]:
arr =  np.array([1,2,3,4,5,6]).reshape(2,3)

In [105]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [106]:
np.ravel(arr, order =  'F') # 'F' stands for FORTRAN -  column major traversal

array([1, 4, 2, 5, 3, 6])

In [107]:
np.ravel(arr, order =  'C') # 'C' stands for C Languange -  row major traversal

array([1, 2, 3, 4, 5, 6])

In [108]:
np.ravel(arr, order =  'A')  # As per current memory allocation - fortran 

array([1, 2, 3, 4, 5, 6])

In [109]:
np.ravel(arr, order =  'K') 

array([1, 2, 3, 4, 5, 6])

In [119]:
arr.transpose().flatten()

array([1, 4, 2, 5, 3, 6])

In [120]:
_

array([1, 4, 2, 5, 3, 6])

In [121]:
print(4)

4


In [122]:
_

array([1, 4, 2, 5, 3, 6])

## Practice Q

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]

Steps to Perform:

Explore the key attributes of NumPy arrays, including ndim, shape, size, dtype, itemsize, and data.
Demonstrate important NumPy array functions such as reshape, flatten, and transpose.