# Numpy

## Agenda
- Fundamentals of numpy
  - Advantages
  - Numpy Installation and import
- Arrays
  - Creating Numpy arrays
- Attributes
- Array Functions
  - Arithmetic
  - Statistical
  - String
  - Miscellaneous
- Array Indexing and Slicing

## Fundamentals of Numpy
Numpy (Numerical Python) is a free, open source python library which is primrily used for mathematical computations. it is prefered over the traditional math module in python for math computation as numpy process the data if a faster way than traditional python. Numpy achieves this by utilizing the arrays (Collection of data arranged in a contiguos memory )

In [1]:
import time
import numpy as np

In [2]:
time.time()  # gives the time elapsed since epoch(1-1-1970, 00:00:00) in seconds

1736433015.9258747

In [3]:
time.time() 

1736433015.9484406

In [4]:
X =  np.random.rand(100000000)   # Generated random floating point numbers

In [5]:
start = time.time()
m =  sum(X)/100000000  # mean using traditional python
stop = time.time()
print(stop- start)

16.696895599365234


In [6]:
start = time.time()
m =  np.mean(X)  # mean calculation using numpy library
stop = time.time()
print(stop- start)

0.30915045738220215


Dated -  08-01-2025

In [7]:
# Install numpy
# pip(prefered python installer) install numpy

In [8]:
pip install numpy

In [9]:
## import the library - it allows to use the library and its content for the current file.

import numpy as np

### Creation of arrays using numpy.
There are two ways by which arrays can be formed using numpy
- using the inbulit array() function  - converts other sequential  data structure to form array
- using miscellaneous functions - generates arrays using some conditions.
  
#### Arrays 
arrays is a collection of homogeneous data elements arranged in contiguos manner. These are represented as space seperated values enclosed within square brackets in python. arrays can attain any number of dimensions i.e. an array is python can be 0 dimensional, 1 dimensional, 2 dimensional, n-dimensional. The numpy arrays are often termed as ndarray.

#### creating arrays using array function

In [10]:
# creating a zero dimensional array
## we can create a 0darray by passing a scalar value inside the numpy array function

zero_d_array =  np.array(5)
print(zero_d_array)
print(type(zero_d_array))
## ndarray attributes
print(f'The Number of dimensions is {zero_d_array.ndim}')  # gives the number of dimensions of the array
print(f'The shape of the array is {zero_d_array.shape}') # The number of elements in each dimension
print(f'The Size of the array is {zero_d_array.size}') # Total number of elements in the array
print(f'Elements data type in the array is {zero_d_array.dtype}') # Datatype of the elements of the array

5
<class 'numpy.ndarray'>
The Number of dimensions is 0
The shape of the array is ()
The Size of the array is 1
Elements data type in the array is int32


In [11]:
# creating a One dimensional array
## we can create a 1darray by passing a list of values inside the numpy array function

one_d_array =  np.array([1,2,3,4,5])
print(one_d_array)
print(type(one_d_array))
## ndarray attributes
print(f'The Number of dimensions is {one_d_array.ndim}')  # 1
print(f'The shape of the array is {one_d_array.shape}') # (5,)
print(f'The Size of the array is {one_d_array.size}') # 5
print(f'Elements data type in the array is {one_d_array.dtype}') # int32

[1 2 3 4 5]
<class 'numpy.ndarray'>
The Number of dimensions is 1
The shape of the array is (5,)
The Size of the array is 5
Elements data type in the array is int32


In [12]:
# creating a Two dimensional array
## we can create a 2darray by passing a list of lists of values inside the numpy array function

two_d_array =  np.array([[1,2,3,4,5], [11,12,13,14,15], [21,22, 23, 24, 25]])
print(two_d_array)
print(type(two_d_array))
## ndarray attributes
print(f'The Number of dimensions is {two_d_array.ndim}')  # 2
print(f'The shape of the array is {two_d_array.shape}') # (3,5)
print(f'The Size of the array is {two_d_array.size}') # 15
print(f'Elements data type in the array is {two_d_array.dtype}') # int32

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
<class 'numpy.ndarray'>
The Number of dimensions is 2
The shape of the array is (3, 5)
The Size of the array is 15
Elements data type in the array is int32


In [13]:
## For unequal number of elements in lists

example = np.array([[1,2,3,4,5], [11,12,13,14], [21,22, 23, 24, 25]], dtype = 'object')
print(example)
print(example.shape)

[list([1, 2, 3, 4, 5]) list([11, 12, 13, 14]) list([21, 22, 23, 24, 25])]
(3,)


In [14]:
# creating a Three dimensional array
## we can create a 3darray by passing a list of lists of lists of values inside the numpy array function

three_d_array =  np.array([[[1, 2, 3,4], [4, 5, 6,4], [7, 8, 9,4]],
                         [[10, 11, 12,4], [13, 14, 15,4], [16, 17, 18,4]]])
print(three_d_array)
print(type(three_d_array))
## ndarray attributes
print(f'The Number of dimensions is {three_d_array.ndim}')  # 3
print(f'The shape of the array is {three_d_array.shape}') # (2,3,4)
print(f'The Size of the array is {three_d_array.size}') # 24
print(f'Elements data type in the array is {three_d_array.dtype}') # int32

[[[ 1  2  3  4]
  [ 4  5  6  4]
  [ 7  8  9  4]]

 [[10 11 12  4]
  [13 14 15  4]
  [16 17 18  4]]]
<class 'numpy.ndarray'>
The Number of dimensions is 3
The shape of the array is (2, 3, 4)
The Size of the array is 24
Elements data type in the array is int32


In [15]:
example =  np.array([[1,2,3], [4,5,6], [7,8,9], [11, 12, 13]])

In [16]:
example.dtype

dtype('int32')

In [17]:
print(example.itemsize) # it gives the memory alloted to one value in the array in bytes

4


In [18]:
print(example.data) # gives the memory address of the array block

### Basic Array functions
- transpose
- reshape
- flatten
- ravel
- argmin
- argmax

In [19]:
example =  np.array([728, 482, 564, 926, 285, 156, 434,  22, 807, 719, 472, 999, 531,
       336, 325, 444, 456,  62, 567, 826])

In [20]:
# reshape() -  allows to modify the dimensions of the array with a constraint the new array with modified
# dimensions will have same size as original array
## syntax -  <arrayname>.reshape(<new_shape>). it a creates a modified copy of the array in the
## memory and doesnot alter the original array untill reassigned

In [21]:
print(example.ndim)
print(example.shape)
print(example.size)

1
(20,)
20


In [22]:
example.reshape(2,5,2)

array([[[728, 482],
        [564, 926],
        [285, 156],
        [434,  22],
        [807, 719]],

       [[472, 999],
        [531, 336],
        [325, 444],
        [456,  62],
        [567, 826]]])

In [23]:
example2d = example.reshape(4,5)

In [24]:
print(example2d)

[[728 482 564 926 285]
 [156 434  22 807 719]
 [472 999 531 336 325]
 [444 456  62 567 826]]


In [25]:
## transpose() -  it is used to take transpose of the array similar to matrix i.e. 
# rows are converted to columns and vice versa . it a creates a modified copy of the array in the
# memory and doesnot alter the original array untill reassigned

In [26]:
print(example2d)
print(example2d.shape)

[[728 482 564 926 285]
 [156 434  22 807 719]
 [472 999 531 336 325]
 [444 456  62 567 826]]
(4, 5)


In [27]:
print(example2d.transpose())
print(example2d.transpose().shape)

[[728 156 472 444]
 [482 434 999 456]
 [564  22 531  62]
 [926 807 336 567]
 [285 719 325 826]]
(5, 4)


In [28]:
## flatten() -  used to convert any dimensional array to 1d array
example2d.flatten()

array([728, 482, 564, 926, 285, 156, 434,  22, 807, 719, 472, 999, 531,
       336, 325, 444, 456,  62, 567, 826])

In [29]:
## ravel() -  used to convert any dimensional array to 1 dimensional array. it also allow to read the array in 
# either row major or column major form
## syntax -  np.ravel(<arrayname>, order = <'F','C','A','K'>)

In [30]:
arr =  np.array([1,2,3,4,5,6]).reshape(2,3)

In [31]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [32]:
np.ravel(arr, order =  'F') # 'F' stands for FORTRAN -  column major traversal

array([1, 4, 2, 5, 3, 6])

In [33]:
np.ravel(arr, order =  'C') # 'C' stands for C Languange -  row major traversal

array([1, 2, 3, 4, 5, 6])

In [34]:
np.ravel(arr, order =  'A')  # As per current memory allocation - fortran 

array([1, 2, 3, 4, 5, 6])

In [35]:
np.ravel(arr, order =  'K') 

array([1, 2, 3, 4, 5, 6])

In [36]:
arr.transpose().flatten()

array([1, 4, 2, 5, 3, 6])

In [37]:
_

array([1, 4, 2, 5, 3, 6])

In [38]:
print(4)

4


In [39]:
_

array([1, 4, 2, 5, 3, 6])

## Practice Q

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]

Steps to Perform:

Explore the key attributes of NumPy arrays, including ndim, shape, size, dtype, itemsize, and data.
Demonstrate important NumPy array functions such as reshape, flatten, and transpose.

**Dated -  09-01-2025**

In [40]:
temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]
arr = np.array(temperatures)

In [47]:
print(arr.argmin()) # it gives the index of the minimum value in the array
print(arr.argmax()) # it gives the index of the maximum value in the array
print(arr.min()) # it gives the minimum value in the array
print(arr.max()) # it gives the maximum value in the array

2
4
74.5
82.6


In [61]:
# Arithmetic functions -  

a1 = np.array([1,2,3])
a2 = np.array([2,8,9])
b1 = np.array([1,5,7])
b2 = np.array([8,9])
c1 = np.array([1,2,6])
c2 = np.array([3,7,17])

In [53]:
## Addition - Element wise 
print(a1+a2) # using  addition operator of python
print(np.add(a1,a2))  # using the numpy add function

[ 3 10 12]
[ 3 10 12]


In [54]:
## Subtraction - Element wise 
print(a1 - a2) # using  subtraction operator of python
print(np.subtract(a1,a2))  # using the numpy subtract function

[-1 -6 -6]
[-1 -6 -6]


In [55]:
## multiplication - Element wise 
print(a1 * a2) # using  multiplication operator of python
print(np.multiply(a1,a2))  # using the numpy multiply function

[ 2 16 27]
[ 2 16 27]


In [56]:
## division - Element wise 
print(a1 / a2) # using  Division operator of python
print(np.divide(a1,a2))  # using the numpy divide function

[0.5        0.25       0.33333333]
[0.5        0.25       0.33333333]


In [57]:
## modulus/remainder - Element wise 
print(a1%a2) # using  modulus operator of python
print(np.mod(a1,a2))  # using the numpy mod function

[1 2 3]
[1 2 3]


In [58]:
## Power - Element wise 
print(a1**a2) # using  Exponential operator of python
print(np.power(a1,a2))  # using the numpy power function

[    1   256 19683]
[    1   256 19683]


In [62]:
np.mod(c2, c1)

array([0, 1, 5])

In [63]:
## Floor Division - Element wise 
print(a1//a2) # using  Floor Division operator of python(the nearest integer value moving towrds negative infinity)
print(np.floor_divide(a1,a2))  # using the numpy floor_divide function

[0 0 0]
[0 0 0]


In [75]:
d1 = np.array(['Hello', 'Welcome'])
d2 = np.array([' World', ' Learners'])
str1 =  'Simpli LeaRN'

In [88]:
# Numpy String Functions

print(np.char.add(d1,d2))  # Element wise conactenation of strng array
print(np.char.upper(str1))
print(np.char.lower(str1))
print(np.char.capitalize(str1)) # make first character of string as upper case and remaining lower
print(np.char.title(str1))  # make first character of each word in string as upper case and remaining lower
print(np.char.replace(str1, 'R', 'r'))

['Hello World' 'Welcome Learners']
SIMPLI LEARN
simpli learn
Simpli learn
Simpli Learn
Simpli LearN


In [81]:
print(np.char.add(d1, str1)) 

['HelloSimpli LeaRN' 'WelcomeSimpli LeaRN']


In [87]:
np.e   # euler's number

2.718281828459045

In [89]:
# Statistical Functions 

In [110]:
arr2 = np.array([11,22,33,44,55, 13,7,3])

In [115]:
print(np.sum(arr2)) # sum of all elements in the array
print(np.mean(arr2)) # average of the values in the array. 
print(np.average(arr2)) # average of the values in the array. 
print(np.median(arr2)) # central value in the sorted array
print(np.percentile(arr2, 50)) # gives the 50th percentile(median value)
print(np.percentile(arr2, 75)) # gives the 75th percentile(Q3)
print(np.percentile(arr2, 25)) # gives the 25th percentile(Q1)
print(np.cumsum(arr2)) # gives the cumulative sum
print(np.std(arr2)) # gives the standard Deviation
print(np.var(arr2)) # gives the variance - Square of std

print(np.cov(c1,c2)) # gives the covariance matrix of array
print(np.corrcoef(c1,c2)) # gives the correlation matrix of array

188
23.5
23.5
17.5
17.5
35.75
10.0
[ 11  33  66 110 165 178 185 188]
17.549928774784245
308.0
[[ 7. 19.]
 [19. 52.]]
[[1.         0.99587059]
 [0.99587059 1.        ]]


In [126]:
# Indexing - indexing is used to access, modify elements in the array

In [129]:
a = np.arange(0,20).reshape(4,5)

In [130]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [135]:
print(a[2,3])
print(a[-2,-2])
print(a[-2,3])
print(a[2,-2])

13
13
13
13


In [140]:
print(np.where(a==19)[0], np.where(a==19)[1])

[3] [4]


In [142]:
a[2,3] = 100

In [143]:
print(a)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12 100  14]
 [ 15  16  17  18  19]]


In [150]:
# Slicing

a[[1,2],1:4]

array([[  6,   7,   8],
       [ 11,  12, 100]])

In [152]:
print(a[0:3:2, 0:5:2])

[[ 0  2  4]
 [10 12 14]]
